baseURL = 'https://touches-grasses.fr/'
languageCode = 'fr-fr'
title = ' Touches Grasses'
theme = "archie"
copyright = "© Touches Grasses"
pygmentsstyle = "solarized-light"
defaultContentLanguage = "fr"

[languages]
  [languages.en]
    contentDir = 'content/posts/en'
    languageName = 'English'
    languageCode = "en"
    weight = 20
  [languages.fr]
    contentDir = 'content/posts/fr'
    languageName = 'Français'
    languageCode = "fr"
    weight = 10

[params]
 	customcss = ["css/everforest.css"]
  customDarkCSS = ["css/everforest-dark.css"]
  mode = "light"
  description = "Nettoie ton clavier et sors de ta bulle d'écho dans ce blog tech purement humain et empreint de liberté."

[[params.social]]
name = "GitHub"
icon = "github"

[[menu.main]]
name = "FR"
url = "/"
weight = 2

[[menu.main]]
name = "EN"
url = "/en"
weight = 3

[[menu.posts]]
name = "Home"
url = "/"
weight = 1
