baseURL = 'https://blog.vagahbond.com/'
languageCode = 'fr-fr'
title = 'Le blog de Vagahbond'
theme = "archie"
copyright = "© Vagahbond"
pygmentsstyle = "solarized-light"

[params]
 	customcss = ["css/everforest.css"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/vagahbond"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2
